spring:
  application:
    name: hello-spring-cloud-service-admin

server:
  port: 8762


  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      

  zipkin:
    base-url: http://localhost:9411      